#!/usr/bin/env bash

cd ~/Music

numberOfSongsOld=`expr $((ls -1A) | wc -l ) - 1`

songsToDownload=`sed '/^\s*$/d' toDownload.txt`

toDownload=`grep -cvx '[[:space:]]*' toDownload.txt`

i=1

for song in $songsToDownload 
do
    echo Downloading song $i out of $toDownload
    youtube-dl -x --audio-format mp3 $song > /dev/null 2>&1
	i=`expr $i + 1`
done

numberOfSongsNow=`expr $((ls -1A) | wc -l ) - 1`

if [ $numberOfSongsNow -eq $(expr $numberOfSongsOld + $toDownload ) ]; then
    echo > toDownload.txt
fi

