#!/usr/bin/env bash

# Sets the background given as argument.

# Check if file exists
if [ -f $1 ]; then
    # Check if file is an image
    if [[ $1 == *.jpg ]] || [[ $1 == *.png ]]; then
        fullpath=`readlink -f $1`
        feh --bg-scale $fullpath
    fi
fi

