#!/usr/bin/env bash

# Sets the background given as argument.

# Check if file exists
if [ -f $1 ]; then
    # Check if file is an image
    if [[ $1 == *.jpg ]] || [[ $1 == *.png ]]; then
        feh --bg-scale $1
    fi
fi
