#!/usr/bin/env bash

#isSpotifyRunning=

playbackStatus=$(spotifycli --playbackstatus)

if [ "$playbackStatus" = ▶ ]; then
    playbackStatus='▮▮'
else
    playbackStatus='▶'
fi

song=$(spotifycli --song)
artist=$(spotifycli --artist)

if [ "$song" = "Spotify" ] && [ artist ]; then
    echo "$playbackStatus Annoying Advertisement"
else
    echo "$playbackStatus $song - $artist"
fi
